export default [
  {
    text: '北京市',
    level: '1',
    value: '110000',
    children: [{ value: '110100', text: '北京市', province: '北京市' }],
  },
  {
    text: '天津市',
    level: '1',
    value: '120000',
    children: [{ value: '120100', text: '天津市', province: '天津市' }],
  },
  {
    text: '河北省',
    level: '1',
    value: '130000',
    children: [
      { value: '130100', text: '石家庄市', province: '河北省' },
      { value: '130200', text: '唐山市', province: '河北省' },
      { value: '130300', text: '秦皇岛市', province: '河北省' },
      { value: '130400', text: '邯郸市', province: '河北省' },
      { value: '130500', text: '邢台市', province: '河北省' },
      { value: '130600', text: '保定市', province: '河北省' },
      { value: '130681', text: '涿州市', province: '河北省' },
      { value: '130682', text: '定州市', province: '河北省' },
      { value: '130683', text: '安国市', province: '河北省' },
      { value: '130684', text: '高碑店市', province: '河北省' },
      { value: '130700', text: '张家口市', province: '河北省' },
      { value: '130800', text: '承德市', province: '河北省' },
      { value: '130900', text: '沧州市', province: '河北省' },
      { value: '131000', text: '廊坊市', province: '河北省' },
      { value: '131100', text: '衡水市', province: '河北省' },
    ],
  },
  {
    text: '山西省',
    level: '1',
    value: '140000',
    children: [
      { value: '140100', text: '太原市', province: '山西省' },
      { value: '140200', text: '大同市', province: '山西省' },
      { value: '140300', text: '阳泉市', province: '山西省' },
      { value: '140400', text: '长治市', province: '山西省' },
      { value: '140500', text: '晋城市', province: '山西省' },
      { value: '140600', text: '朔州市', province: '山西省' },
      { value: '140700', text: '晋中市', province: '山西省' },
      { value: '140800', text: '运城市', province: '山西省' },
      { value: '140900', text: '忻州市', province: '山西省' },
      { value: '141000', text: '临汾市', province: '山西省' },
      { value: '141100', text: '吕梁市', province: '山西省' },
    ],
  },
  {
    text: '内蒙古自治区',
    level: '1',
    value: '150000',
    children: [
      { value: '150100', text: '呼和浩特市', province: '内蒙古自治区' },
      { value: '150200', text: '包头市', province: '内蒙古自治区' },
      { value: '150300', text: '乌海市', province: '内蒙古自治区' },
      { value: '150400', text: '赤峰市', province: '内蒙古自治区' },
      { value: '150500', text: '通辽市', province: '内蒙古自治区' },
      { value: '150600', text: '鄂尔多斯市', province: '内蒙古自治区' },
      { value: '150700', text: '呼伦贝尔市', province: '内蒙古自治区' },
      { value: '150800', text: '巴彦淖尔市', province: '内蒙古自治区' },
      { value: '150900', text: '乌兰察布市', province: '内蒙古自治区' },
      { value: '152200', text: '兴安盟', province: '内蒙古自治区' },
      { value: '152500', text: '锡林郭勒盟', province: '内蒙古自治区' },
      { value: '152900', text: '阿拉善盟', province: '内蒙古自治区' },
    ],
  },
  {
    text: '辽宁省',
    level: '1',
    value: '210000',
    children: [
      { value: '210100', text: '沈阳市', province: '辽宁省' },
      { value: '210200', text: '大连市', province: '辽宁省' },
      { value: '210300', text: '鞍山市', province: '辽宁省' },
      { value: '210400', text: '抚顺市', province: '辽宁省' },
      { value: '210500', text: '本溪市', province: '辽宁省' },
      { value: '210600', text: '丹东市', province: '辽宁省' },
      { value: '210700', text: '锦州市', province: '辽宁省' },
      { value: '210800', text: '营口市', province: '辽宁省' },
      { value: '210900', text: '阜新市', province: '辽宁省' },
      { value: '211000', text: '辽阳市', province: '辽宁省' },
      { value: '211100', text: '盘锦市', province: '辽宁省' },
      { value: '211200', text: '铁岭市', province: '辽宁省' },
      { value: '211300', text: '朝阳市', province: '辽宁省' },
      { value: '211400', text: '葫芦岛市', province: '辽宁省' },
    ],
  },
  {
    text: '吉林省',
    level: '1',
    value: '220000',
    children: [
      { value: '220100', text: '长春市', province: '吉林省' },
      { value: '220200', text: '吉林市', province: '吉林省' },
      { value: '220300', text: '四平市', province: '吉林省' },
      { value: '220400', text: '辽源市', province: '吉林省' },
      { value: '220500', text: '通化市', province: '吉林省' },
      { value: '220600', text: '白山市', province: '吉林省' },
      { value: '220700', text: '松原市', province: '吉林省' },
      { value: '220800', text: '白城市', province: '吉林省' },
      { value: '222400', text: '延边朝鲜族自治州', province: '吉林省' },
    ],
  },
  {
    text: '黑龙江省',
    level: '1',
    value: '230000',
    children: [
      { value: '230100', text: '哈尔滨市', province: '黑龙江省' },
      { value: '230200', text: '齐齐哈尔市', province: '黑龙江省' },
      { value: '230300', text: '鸡西市', province: '黑龙江省' },
      { value: '230400', text: '鹤岗市', province: '黑龙江省' },
      { value: '230500', text: '双鸭山市', province: '黑龙江省' },
      { value: '230600', text: '大庆市', province: '黑龙江省' },
      { value: '230700', text: '伊春市', province: '黑龙江省' },
      { value: '230800', text: '佳木斯市', province: '黑龙江省' },
      { value: '230900', text: '七台河市', province: '黑龙江省' },
      { value: '231000', text: '牡丹江市', province: '黑龙江省' },
      { value: '231100', text: '黑河市', province: '黑龙江省' },
      { value: '231200', text: '绥化市', province: '黑龙江省' },
      { value: '232700', text: '大兴安岭地区', province: '黑龙江省' },
    ],
  },
  {
    text: '上海市',
    level: '1',
    value: '310000',
    children: [{ value: '310100', text: '上海市', province: '上海市' }],
  },
  {
    text: '江苏省',
    level: '1',
    value: '320000',
    children: [
      { value: '320100', text: '南京市', province: '江苏省' },
      { value: '320200', text: '无锡市', province: '江苏省' },
      { value: '320300', text: '徐州市', province: '江苏省' },
      { value: '320400', text: '常州市', province: '江苏省' },
      { value: '320500', text: '苏州市', province: '江苏省' },
      { value: '320600', text: '南通市', province: '江苏省' },
      { value: '320700', text: '连云港市', province: '江苏省' },
      { value: '320800', text: '淮安市', province: '江苏省' },
      { value: '320900', text: '盐城市', province: '江苏省' },
      { value: '321000', text: '扬州市', province: '江苏省' },
      { value: '321100', text: '镇江市', province: '江苏省' },
      { value: '321200', text: '泰州市', province: '江苏省' },
      { value: '321300', text: '宿迁市', province: '江苏省' },
    ],
  },
  {
    text: '浙江省',
    level: '1',
    value: '330000',
    children: [
      { value: '330100', text: '杭州市', province: '浙江省' },
      { value: '330200', text: '宁波市', province: '浙江省' },
      { value: '330300', text: '温州市', province: '浙江省' },
      { value: '330400', text: '嘉兴市', province: '浙江省' },
      { value: '330500', text: '湖州市', province: '浙江省' },
      { value: '330600', text: '绍兴市', province: '浙江省' },
      { value: '330700', text: '金华市', province: '浙江省' },
      { value: '330800', text: '衢州市', province: '浙江省' },
      { value: '330900', text: '舟山市', province: '浙江省' },
      { value: '331000', text: '台州市', province: '浙江省' },
      { value: '331100', text: '丽水市', province: '浙江省' },
    ],
  },
  {
    text: '安徽省',
    level: '1',
    value: '340000',
    children: [
      { value: '340100', text: '合肥市', province: '安徽省' },
      { value: '340200', text: '芜湖市', province: '安徽省' },
      { value: '340300', text: '蚌埠市', province: '安徽省' },
      { value: '340400', text: '淮南市', province: '安徽省' },
      { value: '340500', text: '马鞍山市', province: '安徽省' },
      { value: '340600', text: '淮北市', province: '安徽省' },
      { value: '340700', text: '铜陵市', province: '安徽省' },
      { value: '340800', text: '安庆市', province: '安徽省' },
      { value: '341000', text: '黄山市', province: '安徽省' },
      { value: '341100', text: '滁州市', province: '安徽省' },
      { value: '341200', text: '阜阳市', province: '安徽省' },
      { value: '341300', text: '宿州市', province: '安徽省' },
      { value: '341500', text: '六安市', province: '安徽省' },
      { value: '341600', text: '亳州市', province: '安徽省' },
      { value: '341700', text: '池州市', province: '安徽省' },
      { value: '341800', text: '宣城市', province: '安徽省' },
    ],
  },
  {
    text: '福建省',
    level: '1',
    value: '350000',
    children: [
      { value: '350100', text: '福州市', province: '福建省' },
      { value: '350200', text: '厦门市', province: '福建省' },
      { value: '350300', text: '莆田市', province: '福建省' },
      { value: '350400', text: '三明市', province: '福建省' },
      { value: '350500', text: '泉州市', province: '福建省' },
      { value: '350600', text: '漳州市', province: '福建省' },
      { value: '350700', text: '南平市', province: '福建省' },
      { value: '350800', text: '龙岩市', province: '福建省' },
      { value: '350900', text: '宁德市', province: '福建省' },
    ],
  },
  {
    text: '江西省',
    level: '1',
    value: '360000',
    children: [
      { value: '360100', text: '南昌市', province: '江西省' },
      { value: '360200', text: '景德镇市', province: '江西省' },
      { value: '360300', text: '萍乡市', province: '江西省' },
      { value: '360400', text: '九江市', province: '江西省' },
      { value: '360500', text: '新余市', province: '江西省' },
      { value: '360600', text: '鹰潭市', province: '江西省' },
      { value: '360700', text: '赣州市', province: '江西省' },
      { value: '360800', text: '吉安市', province: '江西省' },
      { value: '360900', text: '宜春市', province: '江西省' },
      { value: '361000', text: '抚州市', province: '江西省' },
      { value: '361100', text: '上饶市', province: '江西省' },
    ],
  },
  {
    text: '山东省',
    level: '1',
    value: '370000',
    children: [
      { value: '370100', text: '济南市', province: '山东省' },
      { value: '370200', text: '青岛市', province: '山东省' },
      { value: '370300', text: '淄博市', province: '山东省' },
      { value: '370400', text: '枣庄市', province: '山东省' },
      { value: '370500', text: '东营市', province: '山东省' },
      { value: '370600', text: '烟台市', province: '山东省' },
      { value: '370700', text: '潍坊市', province: '山东省' },
      { value: '370800', text: '济宁市', province: '山东省' },
      { value: '370900', text: '泰安市', province: '山东省' },
      { value: '371000', text: '威海市', province: '山东省' },
      { value: '371100', text: '日照市', province: '山东省' },
      { value: '371300', text: '临沂市', province: '山东省' },
      { value: '371400', text: '德州市', province: '山东省' },
      { value: '371500', text: '聊城市', province: '山东省' },
      { value: '371600', text: '滨州市', province: '山东省' },
      { value: '371700', text: '菏泽市', province: '山东省' },
    ],
  },
  {
    text: '河南省',
    level: '1',
    value: '410000',
    children: [
      { value: '410100', text: '郑州市', province: '河南省' },
      { value: '410200', text: '开封市', province: '河南省' },
      { value: '410300', text: '洛阳市', province: '河南省' },
      { value: '410400', text: '平顶山市', province: '河南省' },
      { value: '410500', text: '安阳市', province: '河南省' },
      { value: '410600', text: '鹤壁市', province: '河南省' },
      { value: '410700', text: '新乡市', province: '河南省' },
      { value: '410800', text: '焦作市', province: '河南省' },
      { value: '410900', text: '濮阳市', province: '河南省' },
      { value: '411000', text: '许昌市', province: '河南省' },
      { value: '411100', text: '漯河市', province: '河南省' },
      { value: '411200', text: '三门峡市', province: '河南省' },
      { value: '411300', text: '南阳市', province: '河南省' },
      { value: '411400', text: '商丘市', province: '河南省' },
      { value: '411500', text: '信阳市', province: '河南省' },
      { value: '411600', text: '周口市', province: '河南省' },
      { value: '411700', text: '驻马店市', province: '河南省' },
      { value: '419001', text: '济源市', province: '河南省' },
    ],
  },
  {
    text: '湖北省',
    level: '1',
    value: '420000',
    children: [
      { value: '420100', text: '武汉市', province: '湖北省' },
      { value: '420200', text: '黄石市', province: '湖北省' },
      { value: '420300', text: '十堰市', province: '湖北省' },
      { value: '420500', text: '宜昌市', province: '湖北省' },
      { value: '420600', text: '襄阳市', province: '湖北省' },
      { value: '420700', text: '鄂州市', province: '湖北省' },
      { value: '420800', text: '荆门市', province: '湖北省' },
      { value: '420900', text: '孝感市', province: '湖北省' },
      { value: '421000', text: '荆州市', province: '湖北省' },
      { value: '421100', text: '黄冈市', province: '湖北省' },
      { value: '421200', text: '咸宁市', province: '湖北省' },
      { value: '421300', text: '随州市', province: '湖北省' },
      { value: '422800', text: '恩施土家族苗族自治州', province: '湖北省' },
      { value: '429004', text: '仙桃市', province: '湖北省' },
      { value: '429005', text: '潜江市', province: '湖北省' },
      { value: '429006', text: '天门市', province: '湖北省' },
      { value: '429021', text: '神农架林区', province: '湖北省' },
    ],
  },
  {
    text: '湖南省',
    level: '1',
    value: '430000',
    children: [
      { value: '430100', text: '长沙市', province: '湖南省' },
      { value: '430200', text: '株洲市', province: '湖南省' },
      { value: '430300', text: '湘潭市', province: '湖南省' },
      { value: '430400', text: '衡阳市', province: '湖南省' },
      { value: '430500', text: '邵阳市', province: '湖南省' },
      { value: '430600', text: '岳阳市', province: '湖南省' },
      { value: '430700', text: '常德市', province: '湖南省' },
      { value: '430800', text: '张家界市', province: '湖南省' },
      { value: '430900', text: '益阳市', province: '湖南省' },
      { value: '431000', text: '郴州市', province: '湖南省' },
      { value: '431100', text: '永州市', province: '湖南省' },
      { value: '431200', text: '怀化市', province: '湖南省' },
      { value: '431300', text: '娄底市', province: '湖南省' },
      { value: '433100', text: '湘西土家族苗族自治州', province: '湖南省' },
    ],
  },
  {
    text: '广东省',
    level: '1',
    value: '440000',
    children: [
      { value: '440100', text: '广州市', province: '广东省' },
      { value: '440200', text: '韶关市', province: '广东省' },
      { value: '440300', text: '深圳市', province: '广东省' },
      { value: '440400', text: '珠海市', province: '广东省' },
      { value: '440500', text: '汕头市', province: '广东省' },
      { value: '440600', text: '佛山市', province: '广东省' },
      { value: '440700', text: '江门市', province: '广东省' },
      { value: '440800', text: '湛江市', province: '广东省' },
      { value: '440900', text: '茂名市', province: '广东省' },
      { value: '441200', text: '肇庆市', province: '广东省' },
      { value: '441300', text: '惠州市', province: '广东省' },
      { value: '441400', text: '梅州市', province: '广东省' },
      { value: '441500', text: '汕尾市', province: '广东省' },
      { value: '441600', text: '河源市', province: '广东省' },
      { value: '441700', text: '阳江市', province: '广东省' },
      { value: '441800', text: '清远市', province: '广东省' },
      { value: '441900', text: '东莞市', province: '广东省' },
      { value: '442000', text: '中山市', province: '广东省' },
      { value: '445100', text: '潮州市', province: '广东省' },
      { value: '445200', text: '揭阳市', province: '广东省' },
      { value: '445300', text: '云浮市', province: '广东省' },
    ],
  },
  {
    text: '广西壮族自治区',
    level: '1',
    value: '450000',
    children: [
      { value: '450100', text: '南宁市', province: '广西壮族自治区' },
      { value: '450200', text: '柳州市', province: '广西壮族自治区' },
      { value: '450300', text: '桂林市', province: '广西壮族自治区' },
      { value: '450400', text: '梧州市', province: '广西壮族自治区' },
      { value: '450500', text: '北海市', province: '广西壮族自治区' },
      { value: '450600', text: '防城港市', province: '广西壮族自治区' },
      { value: '450700', text: '钦州市', province: '广西壮族自治区' },
      { value: '450800', text: '贵港市', province: '广西壮族自治区' },
      { value: '450900', text: '玉林市', province: '广西壮族自治区' },
      { value: '451000', text: '百色市', province: '广西壮族自治区' },
      { value: '451100', text: '贺州市', province: '广西壮族自治区' },
      { value: '451200', text: '河池市', province: '广西壮族自治区' },
      { value: '451300', text: '来宾市', province: '广西壮族自治区' },
      { value: '451400', text: '崇左市', province: '广西壮族自治区' },
    ],
  },
  {
    text: '海南省',
    level: '1',
    value: '460000',
    children: [
      { value: '460100', text: '海口市', province: '海南省' },
      { value: '460200', text: '三亚市', province: '海南省' },
      { value: '460300', text: '三沙市', province: '海南省' },
      { value: '460400', text: '儋州市', province: '海南省' },
      { value: '469001', text: '五指山市', province: '海南省' },
      { value: '469002', text: '琼海市', province: '海南省' },
      { value: '469005', text: '文昌市', province: '海南省' },
      { value: '469006', text: '万宁市', province: '海南省' },
      { value: '469007', text: '东方市', province: '海南省' },
      { value: '469021', text: '定安县', province: '海南省' },
      { value: '469022', text: '屯昌县', province: '海南省' },
      { value: '469023', text: '澄迈县', province: '海南省' },
      { value: '469024', text: '临高县', province: '海南省' },
      { value: '469025', text: '白沙黎族自治县', province: '海南省' },
      { value: '469026', text: '昌江黎族自治县', province: '海南省' },
      { value: '469027', text: '乐东黎族自治县', province: '海南省' },
      { value: '469028', text: '陵水黎族自治县', province: '海南省' },
      { value: '469029', text: '保亭黎族苗族自治县', province: '海南省' },
      { value: '469030', text: '琼中黎族苗族自治县', province: '海南省' },
    ],
  },
  {
    text: '重庆市',
    level: '1',
    value: '500000',
    children: [{ value: '500100', text: '重庆市', province: '重庆市' }],
  },
  {
    text: '四川省',
    level: '1',
    value: '510000',
    children: [
      { value: '510100', text: '成都市', province: '四川省' },
      { value: '510300', text: '自贡市', province: '四川省' },
      { value: '510400', text: '攀枝花市', province: '四川省' },
      { value: '510500', text: '泸州市', province: '四川省' },
      { value: '510600', text: '德阳市', province: '四川省' },
      { value: '510700', text: '绵阳市', province: '四川省' },
      { value: '510800', text: '广元市', province: '四川省' },
      { value: '510900', text: '遂宁市', province: '四川省' },
      { value: '511000', text: '内江市', province: '四川省' },
      { value: '511100', text: '乐山市', province: '四川省' },
      { value: '511300', text: '南充市', province: '四川省' },
      { value: '511400', text: '眉山市', province: '四川省' },
      { value: '511500', text: '宜宾市', province: '四川省' },
      { value: '511600', text: '广安市', province: '四川省' },
      { value: '511700', text: '达州市', province: '四川省' },
      { value: '511800', text: '雅安市', province: '四川省' },
      { value: '511900', text: '巴中市', province: '四川省' },
      { value: '512000', text: '资阳市', province: '四川省' },
      { value: '513200', text: '阿坝藏族羌族自治州', province: '四川省' },
      { value: '513300', text: '甘孜藏族自治州', province: '四川省' },
      { value: '513400', text: '凉山彝族自治州', province: '四川省' },
    ],
  },
  {
    text: '贵州省',
    level: '1',
    value: '520000',
    children: [
      { value: '520100', text: '贵阳市', province: '贵州省' },
      { value: '520200', text: '六盘水市', province: '贵州省' },
      { value: '520300', text: '遵义市', province: '贵州省' },
      { value: '520400', text: '安顺市', province: '贵州省' },
      { value: '520500', text: '毕节市', province: '贵州省' },
      { value: '520600', text: '铜仁市', province: '贵州省' },
      { value: '522300', text: '黔西南布依族苗族自治州', province: '贵州省' },
      { value: '522600', text: '黔东南苗族侗族自治州', province: '贵州省' },
      { value: '522700', text: '黔南布依族苗族自治州', province: '贵州省' },
    ],
  },
  {
    text: '云南省',
    level: '1',
    value: '530000',
    children: [
      { value: '530100', text: '昆明市', province: '云南省' },
      { value: '530300', text: '曲靖市', province: '云南省' },
      { value: '530400', text: '玉溪市', province: '云南省' },
      { value: '530500', text: '保山市', province: '云南省' },
      { value: '530600', text: '昭通市', province: '云南省' },
      { value: '530700', text: '丽江市', province: '云南省' },
      { value: '530800', text: '普洱市', province: '云南省' },
      { value: '530900', text: '临沧市', province: '云南省' },
      { value: '532300', text: '楚雄彝族自治州', province: '云南省' },
      { value: '532500', text: '红河哈尼族彝族自治州', province: '云南省' },
      { value: '532600', text: '文山壮族苗族自治州', province: '云南省' },
      { value: '532800', text: '西双版纳傣族自治州', province: '云南省' },
      { value: '532900', text: '大理白族自治州', province: '云南省' },
      { value: '533100', text: '德宏傣族景颇族自治州', province: '云南省' },
      { value: '533300', text: '怒江傈僳族自治州', province: '云南省' },
      { value: '533400', text: '迪庆藏族自治州', province: '云南省' },
    ],
  },
  {
    text: '西藏自治区',
    level: '1',
    value: '540000',
    children: [
      { value: '540100', text: '拉萨市', province: '西藏自治区' },
      { value: '540200', text: '日喀则市', province: '西藏自治区' },
      { value: '540300', text: '昌都市', province: '西藏自治区' },
      { value: '540400', text: '林芝市', province: '西藏自治区' },
      { value: '540500', text: '山南市', province: '西藏自治区' },
      { value: '540600', text: '那曲市', province: '西藏自治区' },
      { value: '542500', text: '阿里地区', province: '西藏自治区' },
    ],
  },
  {
    text: '陕西省',
    level: '1',
    value: '610000',
    children: [
      { value: '610100', text: '西安市', province: '陕西省' },
      { value: '610200', text: '铜川市', province: '陕西省' },
      { value: '610300', text: '宝鸡市', province: '陕西省' },
      { value: '610400', text: '咸阳市', province: '陕西省' },
      { value: '610500', text: '渭南市', province: '陕西省' },
      { value: '610600', text: '延安市', province: '陕西省' },
      { value: '610700', text: '汉中市', province: '陕西省' },
      { value: '610800', text: '榆林市', province: '陕西省' },
      { value: '610900', text: '安康市', province: '陕西省' },
      { value: '611000', text: '商洛市', province: '陕西省' },
    ],
  },
  {
    text: '甘肃省',
    level: '1',
    value: '620000',
    children: [
      { value: '620100', text: '兰州市', province: '甘肃省' },
      { value: '620200', text: '嘉峪关市', province: '甘肃省' },
      { value: '620300', text: '金昌市', province: '甘肃省' },
      { value: '620400', text: '白银市', province: '甘肃省' },
      { value: '620500', text: '天水市', province: '甘肃省' },
      { value: '620600', text: '武威市', province: '甘肃省' },
      { value: '620700', text: '张掖市', province: '甘肃省' },
      { value: '620800', text: '平凉市', province: '甘肃省' },
      { value: '620900', text: '酒泉市', province: '甘肃省' },
      { value: '621000', text: '庆阳市', province: '甘肃省' },
      { value: '621100', text: '定西市', province: '甘肃省' },
      { value: '621200', text: '陇南市', province: '甘肃省' },
      { value: '622900', text: '临夏回族自治州', province: '甘肃省' },
      { value: '623000', text: '甘南藏族自治州', province: '甘肃省' },
    ],
  },
  {
    text: '青海省',
    level: '1',
    value: '630000',
    children: [
      { value: '630100', text: '西宁市', province: '青海省' },
      { value: '630200', text: '海东市', province: '青海省' },
      { value: '632200', text: '海北藏族自治州', province: '青海省' },
      { value: '632300', text: '黄南藏族自治州', province: '青海省' },
      { value: '632500', text: '海南藏族自治州', province: '青海省' },
      { value: '632600', text: '果洛藏族自治州', province: '青海省' },
      { value: '632700', text: '玉树藏族自治州', province: '青海省' },
      { value: '632800', text: '海西蒙古族藏族自治州', province: '青海省' },
    ],
  },
  {
    text: '宁夏回族自治区',
    level: '1',
    value: '640000',
    children: [
      { value: '640100', text: '银川市', province: '宁夏回族自治区' },
      { value: '640200', text: '石嘴山市', province: '宁夏回族自治区' },
      { value: '640300', text: '吴忠市', province: '宁夏回族自治区' },
      { value: '640400', text: '固原市', province: '宁夏回族自治区' },
      { value: '640500', text: '中卫市', province: '宁夏回族自治区' },
    ],
  },
  {
    text: '新疆维吾尔自治区',
    level: '1',
    value: '650000',
    children: [
      { value: '650100', text: '乌鲁木齐市', province: '新疆维吾尔自治区' },
      { value: '650200', text: '克拉玛依市', province: '新疆维吾尔自治区' },
      { value: '650400', text: '吐鲁番市', province: '新疆维吾尔自治区' },
      { value: '650500', text: '哈密市', province: '新疆维吾尔自治区' },
      { value: '652300', text: '昌吉回族自治州', province: '新疆维吾尔自治区' },
      {
        value: '652700',
        text: '博尔塔拉蒙古自治州',
        province: '新疆维吾尔自治区',
      },
      {
        value: '652800',
        text: '巴音郭楞蒙古自治州',
        province: '新疆维吾尔自治区',
      },
      { value: '652900', text: '阿克苏地区', province: '新疆维吾尔自治区' },
      {
        value: '653000',
        text: '克孜勒苏柯尔克孜自治州',
        province: '新疆维吾尔自治区',
      },
      { value: '653100', text: '喀什地区', province: '新疆维吾尔自治区' },
      { value: '653200', text: '和田地区', province: '新疆维吾尔自治区' },
      {
        value: '654000',
        text: '伊犁哈萨克自治州',
        province: '新疆维吾尔自治区',
      },
      { value: '654200', text: '塔城地区', province: '新疆维吾尔自治区' },
      { value: '654300', text: '阿勒泰地区', province: '新疆维吾尔自治区' },
      { value: '659001', text: '石河子市', province: '新疆维吾尔自治区' },
      { value: '659002', text: '阿拉尔市', province: '新疆维吾尔自治区' },
      { value: '659003', text: '图木舒克市', province: '新疆维吾尔自治区' },
      { value: '659004', text: '五家渠市', province: '新疆维吾尔自治区' },
      { value: '659005', text: '北屯市', province: '新疆维吾尔自治区' },
      { value: '659006', text: '铁门关市', province: '新疆维吾尔自治区' },
      { value: '659007', text: '双河市', province: '新疆维吾尔自治区' },
      { value: '659008', text: '可克达拉市', province: '新疆维吾尔自治区' },
      { value: '659009', text: '昆玉市', province: '新疆维吾尔自治区' },
      { value: '659010', text: '胡杨河市', province: '新疆维吾尔自治区' },
    ],
  },
  {
    text: '台湾省',
    level: '1',
    value: '710000',
    children: [{ text: '台湾省', level: '1', value: '7100' }],
  },
  {
    text: '香港特别行政区',
    level: '1',
    value: '810000',
    children: [{ text: '香港特别行政区', level: '1', value: '8100' }],
  },
  {
    text: '澳门特别行政区',
    level: '1',
    value: '820000',
    children: [{ text: '澳门特别行政区', level: '1', value: '8200' }],
  },
];
